name: Build CV LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile CV LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: "fontawesome"
          working_directory: CV/
          latexmk_use_xelatex: true
          root_file: main.tex
